### ISSUE TITLE
Compatibility with last version of Guzzle

### ISSUE THREAD

**Issue by pvcnt** [stage1/docker-php#126] opened 2015-08-31 12:04 UTC
Hello,

I did not read everything but would it be possible to integrate the latest version of Guzzle? It would make it possible to use docker-php in environments where Guzzle 6 is used.

Thanks.

**Comment by ubermuda** [comment] 2015-09-02 13:35
We could easily check this by bumping guzzle's version and running the unit tests. The test suite is quite comprehensive and I'm confident any problem would be catched by it.

What do you think @joelwurtz ?

**Comment by joelwurtz** [comment] 2015-11-06 15:05
duplicate of #46

**Closed by joelwurtz** 2015-11-06 15:05 UTC
