### ISSUE TITLE
Consider upgrading dependencies to guzzle 5?

### ISSUE THREAD

**Issue by jeremythorson** [stage1/docker-php#114] opened 2015-04-23 16:42 UTC
Has there been any consideration/discussion around updating docker-php's dependencies to leverage a newer release of guzzle (i.e. ~5.*)?

I'm running into a dependency conflict with another library I'd like to use, and upgrading docker-php to support the newer version of guzzle seems a more rational ask than requesting that they downgrade.

**Comment by hacfi** [comment] 2015-04-24 10:26
Hi @jeremythorson, there has been a discussion about this over at #46 but the development hasn’t started.

**Comment by joelwurtz** [comment] 2015-11-06 15:05
duplicate of #46

**Closed by joelwurtz** 2015-11-06 15:05 UTC
